version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kontess-front-end


hooks:
  ApplicationStart:
    - location: latest/scripts/after_deploy_supervisor_restart.sh
      timeout: 500
      runas: root
